QGIS3_PROFILE = ~/.local/share/QGIS/QGIS3/profiles/default
QGIS3_PYTHON3_PLUGIN_SPACE = $(QGIS3_PROFILE)/python/plugins
SURVEX_IMPORT_PLUGIN = $(QGIS3_PYTHON3_PLUGIN_SPACE)/SurvexImport

SURVEX_IMPORT_SOURCE = ./SurvexImport

default: install

install:
	mkdir -p $(SURVEX_IMPORT_PLUGIN)
	cp -v $(SURVEX_IMPORT_SOURCE)/icon.png $(SURVEX_IMPORT_PLUGIN)
	cp -v $(SURVEX_IMPORT_SOURCE)/metadata.txt $(SURVEX_IMPORT_PLUGIN)
	cp -v $(SURVEX_IMPORT_SOURCE)/*.py $(SURVEX_IMPORT_PLUGIN)
	cp -v $(SURVEX_IMPORT_SOURCE)/*.ui $(SURVEX_IMPORT_PLUGIN)
